id: P5390E1AE
initial_creation_type: input
source_metadata:
  title: Guru Padmasambhava
  language: es
  description: 'Prayers to the Precious Guru Padmasambhava or Padmākara (padma ''byung
    gnas), the "Lotus-Born", who is credited with establishing Buddhism in Tibet:'
  volume:
    05b1f495187e404aa9a84acd50c55725:
      title: A Synopsis of Guru Padmasambhava’s Life
      parent: Alak Zenkar Pema Ngödrup Rolwe Dorje
    38240d392ad44cdd9203e2c6fc0d73d0:
      title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
      parent: Dudjom Rinpoche
    c7fc9b0373ca4ae28c22f491bdfc3030:
      title: 'Pearl Droplets of Blessings: A Prayer to the Guru Who Embodies All'
      parent: Chokgyur Dechen Lingpa
    1da7af33b12e41e3b6e93a29bbc7e2bd:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Chokgyur Dechen Lingpa
    4980e6e922ae4762a9c8ad4b36de5331:
      title: The Prayer in Six Vajra Lines
      parent: Chokgyur Dechen Lingpa
    52e1de99605742548c0e3199fe8904cd:
      title: The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma)
      parent: Chokgyur Dechen Lingpa
    4baa27d627bb44e6ac1ba123ac8b410a:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Chokgyur Dechen Lingpa
    63b184b21e854be7956ec0098e5ce328:
      title: The Testament Prayer to Orgyen Rinpoche
      parent: Chokgyur Dechen Lingpa
    86dd80344d5a4dd2aad104cd0d36f2d2:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Chokgyur Dechen Lingpa
    8f5e9e23c03b43eb97af14c63e8d6915:
      title: Threefold Aspiration for Rebirth in Zangdok Palri
      parent: Chokgyur Dechen Lingpa
    33f0df7e2f454309afa29c39135893ab:
      title: 'A Garland of Vajra Words: A Prayer to the Guru'
      parent: Dilgo Khyentse Rinpoche
    7e37058a0bd64d8fa5425fc39ec92171:
      title: 'All Wishes Swiftly Fulfilled: A Prayer to the Mahāguru of Uḍḍiyāna in
        Eight Chapters'
      parent: Dilgo Khyentse Rinpoche
    d444d7008a204488b12e1e9281bf5dbe:
      title: The Prayer to Swiftly Fulfil All Wishes
      parent: Dilgo Khyentse Rinpoche
    940a861751fd4fa5bd99df29961c6b54:
      title: 'The Precious Jewel Essence: A Prayer of the Four Dharmas'
      parent: Dilgo Khyentse Rinpoche
    09c4023e98234eff9954beefa3c82585:
      title: A Very Brief Prayer for Clearing Obstacles from the Path (Barche Lamsel)
      parent: Do Khyentse
    6c348f8f20db4a3dac8be49eb348352b:
      title: 'The Lightning Bolt of Compassion: A Short Prayer that Spontaneously
        Fulfils All Wishes (Sampa Lhundrupma)'
      parent: Do Khyentse
    14ee3b4bcb1640cfb2e2306b3f4c8fe6:
      title: Prayer to Padmasambhava, Longchenpa and Jigme Lingpa
      parent: Dodrupchen Jigme Tenpe Nyima
    55709d54f2e1416a8b27f1f9384545ee:
      title: 'The Adamantine Magical Wheel: Invoking the Profound Pledge of Padmākara,
        the Glorious Victor, to Avert the Final War'
      parent: Dodrupchen Jigme Tenpe Nyima
    97e90b01d4d2403db4b9620b53279da9:
      title: The Prayer to Guru Rinpoche for Attainments
      parent: Dodrupchen Jigme Trinle Özer
    826b27287b604eaba85facb1dcf96119:
      title: A Prayer to Padmasambhava
      parent: Dudjom Lingpa
    1e7a13b92d7e4d93811efabc647d3ea8:
      title: 'A Joyful Chariot for the Fortunate: An Aspiration to Travel to the Copper-Coloured
        Mountain of Glory'
      parent: Dudjom Rinpoche
    1e15bf9911df433fbb5e6fd22a9e442d:
      title: A Short Prayer to the Abbot, the Master and the King
      parent: Dudjom Rinpoche
    1e14f82a40864fffbdf762a3d25c2eac:
      title: 'Drumbeat of the Deathless Vajra: A Fervent Invocation and Prayer'
      parent: Dudjom Rinpoche
    6daf4540bd244780b2536c2e45b0ee65:
      title: The Ornament of Padmasambhava’s Enlightened Vision
      parent: Dudjom Rinpoche
    aecb2137cb8e4780b4ef85f250bf74cc:
      title: The Prayer to Guru Rinpoche that Swiftly Removes Obstacles and Fulfills
        All Wishes
      parent: Dudjom Rinpoche
    be2dc51067df4653b4c8fc415e644ea6:
      title: A Prayer to the Precious Guru from Uḍḍiyāna That Spontaneously Fulfils
        All Wishes
      parent: Dzongter Kunzang Nyima
    c460babf52134203aac5846445e245f7:
      title: 'Cloud Banks of Blessings: A Prayer to Guru Padmasambhava'
      parent: Fifth Dalai Lama
    be0eac845e6048e59fec54ee463358b8:
      title: A Yearning Song of Prayer to Invoke the Wisdom Mind of the Compassionate
        Teacher Padmasambhava
      parent: Fourteenth Dalai Lama
    a1eaa9d8d42849ab81d9ea08d2990730:
      title: A Prayer to Guru Rinpoche That Spontaneously Fulfils All Wishes (from
        the Extremely Secret Assembly of Sugatas)
      parent: Garwang Chökyi Gyaltsen
    5c0008223d6e43d088423b3852c7fa55:
      title: Prayer to Orgyen Rinpoche Invoking His Wisdom Mind
      parent: Gönpo Tseten Rinpoche
    e6ab619e7e294b0193af158cf7113f6d:
      title: The Prayer of the Tenth Days in Guru Rinpoche’s Life Story entitled ‘The
        Nucleus of Blessings’
      parent: Jamgön Kongtrul
    e5902def37af4f19b323e448bc6f13ee:
      title: A Heart Prayer to Orgyen Dorje Chang
      parent: Jamyang Khyentse Chökyi Lodrö
    6a96300c50de429b8e785fda05385a5d:
      title: A Prayer of Aspiration for the Mountain of Glory
      parent: Jamyang Khyentse Chökyi Lodrö
    e3b7d49cb3cf441c888eb07aa9f85c25:
      title: A Prayer to Orgyen Dorje Chang
      parent: Jamyang Khyentse Chökyi Lodrö
    7b7cfecd7a3d49ea843a88fab16a3259:
      title: A Yearning Plea to the Precious Guru
      parent: Jamyang Khyentse Chökyi Lodrö
    fac1aef596b6473898669c84162f6103:
      title: 'Cloud Banks of Blessings: A Prayer to Orgyen Rinpoche'
      parent: Jamyang Khyentse Chökyi Lodrö
    c0377a32fc4041e391d762a1ada1388a:
      title: Prayer of the Wisdom Mind
      parent: Jamyang Khyentse Chökyi Lodrö
    1eca6a4cf46948fbb0679a4b61746481:
      title: Spontaneous Fulfilment of Wishes
      parent: Jamyang Khyentse Chökyi Lodrö
    9abfca383fef42e28ab5424d329435bc:
      title: The Falling Elixir of Blessing
      parent: Jamyang Khyentse Chökyi Lodrö
    be6291bfc94d4659b8432c94a41d78f3:
      title: 'The Fulfilment of Wishes and Aspirations: A Prayer to Ācārya Padmasambhava'
      parent: Jamyang Khyentse Chökyi Lodrö
    a4e68b10559e46bd9f52f68ae9c4015b:
      title: 'The Supreme Bestowal of Twofold Attainment: A Prayer to Orgyen Rinpoche,
        Embodiment of All Sources of Refuge'
      parent: Jamyang Khyentse Chökyi Lodrö
    004c99a701074a538eb46188bcdf9712:
      title: 'The Swift Fulfilment of Aspirations: A Prayer to Glorious Orgyen, King
        of Dharma'
      parent: Jamyang Khyentse Chökyi Lodrö
    c752c97faca24bf4920fe75cba7ed121:
      title: 'The Vajra Words Unveiled: A Commentary on the Düsum Sangyé Prayer to
        the Guru'
      parent: Jamyang Khyentse Chökyi Lodrö
    0e2efa6228e748ffa718bbdb491e2a42:
      title: To Fulfil All Wishes
      parent: Jamyang Khyentse Chökyi Lodrö
    3e1bca4998b74d25af6cdb729ee7105b:
      title: Turning Back the Misfortunes of the Age of Degeneration
      parent: Jamyang Khyentse Chökyi Lodrö
    c77af380fd904c06b2ba8df10fe1c4d8:
      title: 'A Beautiful and Wondrous Udumbara Garland: A Supplication and Summary
        of the Chronicles of Padma, The Life and Liberation of the Precious Guru of
        Uḍḍiyāna'
      parent: Jamyang Khyentse Wangpo
    7563cbf5bfd64192845f880d94ae90a8:
      title: A Brief Prayer to the Precious Master Padmākara for Swiftly Fulfilling
        Wishes
      parent: Jamyang Khyentse Wangpo
    0639ed498c484b40b223809eb828fdf6:
      title: 'The Chariot of the Vidyādharas: An Aspiration Prayer for Travelling
        to the Realm of Lotus Light'
      parent: Jamyang Khyentse Wangpo
    98d51db0f68c48c2985ab65fe0c35db9:
      title: The General Visualization for Prayers to Guru Rinpoche
      parent: Jamyang Khyentse Wangpo
    7f552d86df6a4d1395af0ed098a8de35:
      title: 'The Heart of Blessings: A Brief Anthology of Prayers to Guru Rinpoche
        and the Twenty-Five Disciples, the King and Subjects'
      parent: Jamyang Khyentse Wangpo
    ade47d33edde4108aa9202c7839dd4ca:
      title: 'Turning Back Obstacles and Adverse Circumstances: A Prayer to Orgyen
        Rinpoche, Embodiment of All Sources of Refuge'
      parent: Jamyang Khyentse Wangpo
    82ff9062d9ff430a952ec16d83deea30:
      title: 'Wish-Fulfilling Feast of Siddhis: An Aspiration Prayer to Orgyen Rinpoche,
        the Precious Master of Oddiyana'
      parent: Jamyang Khyentse Wangpo
    2da86f087260472cb35e6233bf45f59f:
      title: A Prayer Invoking the Benefits of the Festival of the Tenth Day
      parent: Jigme Lingpa
    b9f6c00d936c4c5f8023336f92709047:
      title: A Prayer of Devotion, to Make the Tears Fall
      parent: Jigme Lingpa
    2b6ad492c5d045f59ae12da588091080:
      title: Secret Path to the Mountain of Glory—A Prayer of Aspiration for the Copper-Coloured
        Mountain of Glory
      parent: Jigme Lingpa
    373b0d76ebbc40e7af2d8871d952fd24:
      title: Training in the Pure Realms of the Three Kāyas
      parent: Jigme Lingpa
    0c90ef287b9b424db9a67b639f8d48ed:
      title: Prayer to Pema Tötreng Tsal
      parent: Khenchen Ngawang Palzang
    f26fde3b4b804df6b9a8e5764df6d198:
      title: The Prayer that Swiftly Fulfils All Wishes (Sampa Nyur Drupma)
      parent: Longchen Rabjam
    a325676dfc73427f8647d41703adf365:
      title: Prayer to the Indian Mahāpaṇḍita Padmasambhava
      parent: Menlungpa Mikyö Dorje
    c89a2d8e95f5465bbb9615173fe2f42b:
      title: A Plaintive Prayer to Guru Rinpoche
      parent: Minling Chung Rinpoche
    6613e8fb01504e8fa585369ddfbdbc51:
      title: A Brief Prayer for the Spontaneous Fulfilment of Aspirations
      parent: Mipham Rinpoche
    67ba6a4d390c4600b70bb69658e56863:
      title: Recollecting the Deeds of The Tenth Days
      parent: Mipham Rinpoche
    4d3ef4f9617b4981b72f261c1c7ae16f:
      title: The Prayer which is the Source of All True Realization
      parent: Mipham Rinpoche
    c69bb88051f14b72a1374bf6573b5264:
      title: 'The Secret Path of Wisdom: A Prayer of Aspiration for the Mountain of
        Glory'
      parent: Mipham Rinpoche
    6e79fb8cee1e40ee97a8fb11b4f06783:
      title: A Prayer Recalling the Life and Liberation of the Precious Master Padmasambhava
      parent: Nyang Ral Nyima Özer
    4e27c4d9c38249c79be55f9066904f6e:
      title: The Abbreviated Prayer in Seven Chapters
      parent: Nyang Ral Nyima Özer
    f1b866b034b54908ac9ed66500ccb885:
      title: The Prayer to Orgyen Rinpoche that Invokes the Heart of his Wisdom Mind
      parent: Pawo Lerab Tsal
    79273cfa8f884e709f808a010752b5e0:
      title: An Extremely Concise Barché Lamsel—The Prayer for Clearing Obstacles
        from the Path
      parent: Rangrik Dorje
    f1737007061742adad8729238cb07f44:
      title: An Extremely Concise Sampa Lhundrup—Prayer that Spontaneously Fulfils
        All Wishes
      parent: Rangrik Dorje
    812b847a3d9948f0893f62e5fad9da7e:
      title: The Seven Lines that Dispel All Obstacles and Enfold All Profundity
      parent: Rangrik Dorje
    de1f3e87962a486292aca64db60744cb:
      title: 'The Spontaneous Fulfilment of All Wishes: Invoking the Great Guru of
        Uḍḍiyāna'
      parent: Rangrik Dorje
    8039f5b53c3f4ec9bb59034271a32fe8:
      title: 'The Wish-Fulfilling Tree: A Prayer to the All-Embodying Lama Tsokye
        Dorje'
      parent: Rangrik Dorje
    10fb9012f1e545e5a02f5fb346778aa4:
      title: 'Victory Over All Adversity: A Prayer to Invoke Guru Rinpoche’s Wisdom
        for the Swift Fulfilment of Wishes'
      parent: Rangrik Dorje
    e7a488c8d7334262998d00b4a5d1b096:
      title: 'Cloud Banks of Blessings: A Prayer Recounting the Eleven Deeds of the
        Life and Liberation of the Guru from Uḍḍiyāna'
      parent: Ratna Lingpa
    c24dfea8e1a74e6c87c4bf708df57f82:
      title: The Invocation of Uḍḍiyāna on the Tenth Day
      parent: Ratna Lingpa
    b557218900ea4f8788d43fe665848441:
      title: A Prayer To Padmasambhava
      parent: Shechen Gyaltsab Gyurme Pema Namgyal
    7c22da7c90f24d069c0b215a9620c075:
      title: A Prayer to the Vajradhara of Oḍḍiyāna
      parent: Shechen Gyaltsab Gyurme Pema Namgyal
    078de67554c14055a67b3eaca8679088:
      title: 'The Beat of the Vajra Drum: A Prayer'
      parent: Shechen Rabjam Rinpoche
    5953a0a2e3744881971b7c1a52eacd63:
      title: Topical Outline of the Prayer That Swiftly Fulfils All Wishes (Sampa
        Nyur Drupma)
      parent: Outlines
created_at: '2022-03-01T03:50:02.046316'
last_modified_at: '2022-03-01T03:50:02.046320'
